vim.notify("Vim config loaded")

require("plugins")

require("set")
require("autocmd")
require("theme")

require("plugins.alpha")
require("plugins.transparent")
require("plugins.lualine")
require("plugins.which-key")
require("plugins.dressing")
require("plugins.lsp-zero")
require("plugins.treesitter")
require("plugins.cmp")
require("plugins.autopairs")
require("plugins.trouble")
require("plugins.notify")
require("plugins.mini")
require("plugins.fine-cmdline")
require("plugins.instant")
require("plugins.gitsings")
require("plugins.copilot")
