require("mattsivak.packer")

require("mattsivak.plugins.which-key")
require("mattsivak.plugins.treesitter")
require("mattsivak.plugins.transparent")
require("mattsivak.plugins.cloak")
require("mattsivak.plugins.lualine")
require("mattsivak.plugins.indent-blankline")
require("mattsivak.plugins.telescope")
require("mattsivak.plugins.alpha")
require("mattsivak.plugins.neotree")
require("mattsivak.plugins.legendary")
require("mattsivak.plugins.dressing")
require("mattsivak.plugins.notify")

require("mattsivak.lsp")
require("mattsivak.set")
require("mattsivak.theme")
require("mattsivak.autocmd")
